In [1]:
from binarytree import tree
import numpy as np

In [2]:
my_tree = tree(height=2, is_perfect=True)
print(my_tree)


    __0__
   /     \
  2       4
 / \     / \
1   5   3   6



## There are two types of BFS questions:
* Tree
* Graph

# Appendix

## Tree

[102. Binary Level Order Traversal](#102.-Binary-Level-Order-Traversal)

[103. Binary Tree Zigzag Level Order Traversal](#103.-Binary-Tree-Zigzag-Level-Order-Traversal)

[107. Binary Tree Level Order Traversal II](#107.-Binary-Tree-Level-Order-Traversal-II)

[111. Minimum Depth of Binary Tree](#111.-Minimum-Depth-of-Binary-Tree)

[199. Binary Tree Right Side View](#199.-Binary-Tree-Right-Side-View)

[513. Find Bottom Left Tree Value](#513.-Find-Bottom-Left-Tree-Value)

[515. Find Largest Value in Each Tree Row](#515.-Find-Largest-Value-in-Each-Tree-Row)

[1161. Maximum Level of a Binary Tree](#1161.-Maximum-Level-of-a-Binary-Tree)


### N-ary Tree

[429. N-ary Tree Level Order Traversal](#429.-N-ary-Tree-Level-Order-Traversal)

[559. Maximum Depth of N-ary Tree](#559.-Maximum-Depth-of-N-ary-Tree)


## Graph

[200. Number of Islands](#200.-Number-of-Islands)

[286. Walls and Gates](#286.-Walls-and-Gates)

[994. Rotting Oranges](#994.-Rotting-Oranges)

[1091. Shortest Path in Binary Matrix](#1091.-Shortest-Path-in-Binary-Matrix)

# N-ary Breadth First Search

In [3]:
def n_ary_bfs(root):
    output = []
    
    if not root:
        return output
    
    queue = [root]
    
    while queue:
        curr = queue.pop(0)
        output.append(curr.value)
        
        for child in curr.children:
            queue.append(child)
            
    return output

# 559. Maximum Depth of N-ary Tree

In [4]:
def maxDepth(root):
    """
    :type root: Node
    :rtype: int
    """
    max_depth = 0

    if not root:
        return max_depth

    queue = [root] 

    while queue:
        for i in range(len(queue)):
            curr = queue.pop(0)

            for child in curr.children:
                queue.append(child)

        max_depth += 1

    return max_depth

# 429. N-ary Tree Level Order Traversal

In [5]:
def levelOrder(root):
    out = []

    if not root:
        return out

    queue = [root]

    while queue:
        level = []

        for i in range(len(queue)):
            curr = queue.pop(0)
            level.append(curr.val)

            for child in curr.children:
                queue.append(child)

        out.append(level)

    return out

# General Breadth First Search

In [6]:
def bfs(root):
    output = []
    
    if not root:
        return output
    
    queue = [root]
    
    while queue:
        curr = queue.pop(0)
        output.append(curr.value)
        
        if curr.left:
            queue.append(curr.left)
        if curr.right:
            queue.append(curr.right)
            
    return output

print(my_tree)
print("BFS: ", bfs(my_tree))


    __0__
   /     \
  2       4
 / \     / \
1   5   3   6

BFS:  [0, 2, 4, 1, 5, 3, 6]


# 200. Number of Islands

In [7]:
def bfs(grid, row, col):
    dirs = [(-1,0), (1,0), (0,-1), (0,1)]
    queue = [(row, col)]

    while queue:
        i, j = queue.pop(0)

        for x, y in dirs:
            nrow = x + i
            ncol = y + j

            if nrow >= 0 and nrow < len(grid) and \
                ncol >= 0 and ncol < len(grid[0]) and \
                grid[nrow][ncol] == '1':
                grid[nrow][ncol] = '0'
                queue.append((nrow, ncol))

    return


def numIslands(grid):
    """
    :type grid: List[List[str]]
    :rtype: int
    """
    if not grid:
        return 0

    islands = 0
    rows = len(grid)
    cols = len(grid[0])

    for i in range(rows):
        for j in range(cols):
            if grid[i][j] == '1':
                bfs(grid, i, j)
                islands += 1

    return islands

grid = [["1","1","1","1","0"],["1","1","0","1","0"],["1","1","0","0","0"],["0","0","0","0","0"]]
print(np.array(grid))
print('Number of Islands: ', numIslands(grid))

[['1' '1' '1' '1' '0']
 ['1' '1' '0' '1' '0']
 ['1' '1' '0' '0' '0']
 ['0' '0' '0' '0' '0']]
Number of Islands:  1


# 111. Minimum Depth of Binary Tree

In [8]:
def minDepth(root):
    """
    :type root: TreeNode
    :rtype: int
    """
    if not root:
        return 0

    min_depth = 1
    queue = [root]

    while queue:
        for i in range(len(queue)):
            curr = queue.pop(0)

            if not curr.left and not curr.right:
                return min_depth

            if curr.left:
                queue.append(curr.left)
            if curr.right:    
                queue.append(curr.right)

        min_depth += 1

    return min_depth

print(my_tree)
print("Min depth of binary tree: ", minDepth(my_tree))


    __0__
   /     \
  2       4
 / \     / \
1   5   3   6

Min depth of binary tree:  3


# 513. Find Bottom Left Tree Value

Given a binary tree, find the leftmost value in the last row of the tree.

In [9]:
def find_bottom_left_value(root):
    if not root:
        return None
    
    queue = [root]
    
    while queue:
        curr = queue.pop(0)
        
        if curr.right:
            queue.append(curr.right)
        if curr.left:
            queue.append(curr.left)
            
    return curr.value

print(my_tree)
print("Bottom Left Value: ", find_bottom_left_value(my_tree))


    __0__
   /     \
  2       4
 / \     / \
1   5   3   6

Bottom Left Value:  1


# 515. Find Largest Value in Each Tree Row

In [26]:
def largestValues(root):
    out = []

    if not root:
        return out

    queue = [root]
    biggest = -float('inf')
    biggestSoFar = -float('inf')

    while queue:
        size = len(queue)

        for i in range(size):
            curr = queue.pop(0)
            biggestSoFar = curr.value

            if curr.left:
                queue.append(curr.left)
            if curr.right:
                queue.append(curr.right)

            biggest = max(biggest, biggestSoFar)


        out.append(biggest)
        biggest = -float('inf')
        biggestSoFar = -float('inf')

    return out

print(my_tree)
print(largestValues(my_tree))


    __0__
   /     \
  2       4
 / \     / \
1   5   3   6

[0, 4, 6]


# 102. Binary Level Order Traversal

Given a binary tree, return the level order traversal of its nodes' values. (ie, from left to right, level by level).

In [10]:
def level_order_traversal(root):
    output = []
    
    if not root:
        return output
    
    queue = [root]
    
    while queue:
        level = []
        for i in range(len(queue)):
            curr = queue.pop(0)
            level.append(curr.value)
            
            if curr.left:
                queue.append(curr.left)
            if curr.right:
                queue.append(curr.right)
                
        output.append(level)
        
    return output

print(my_tree)
print("Levels: ", level_order_traversal(my_tree))


    __0__
   /     \
  2       4
 / \     / \
1   5   3   6

Levels:  [[0], [2, 4], [1, 5, 3, 6]]


# 107. Binary Tree Level Order Traversal II

Given a binary tree, return the bottom-up level order traversal of its nodes' values. (ie, from left to right, level by level from leaf to root).

In [11]:
def level_order_bottom(root):
    output = []
    
    if not root:
        return output
    
    queue = [root]
    
    while queue:
        level = []
        for i in range(len(queue)):
            curr = queue.pop(0)
            level.append(curr.value)
            
            if curr.left:
                queue.append(curr.left)
            if curr.right:
                queue.append(curr.right)
                
        output.insert(0, level)
            
    return output

print(my_tree)
print("Reverse Levels: ", level_order_bottom(my_tree))


    __0__
   /     \
  2       4
 / \     / \
1   5   3   6

Reverse Levels:  [[1, 5, 3, 6], [2, 4], [0]]


# 1161. Maximum Level of a Binary Tree

Given the root of a binary tree, the level of its root is 1, the level of its children is 2, and so on.

Return the smallest level X such that the sum of all the values of nodes at level X is maximal.

In [12]:
def max_level_sum(root):
    if not root:
        return None

    max_level = 1
    curr_level = 1
    curr_val = -float('inf')

    queue = [root]

    while queue:
        level = []
        for i in range(len(queue)):
            curr = queue.pop(0)
            level.append(curr.value)

            if curr.left:
                queue.append(curr.left)
            if curr.right:
                queue.append(curr.right)

        if sum(level) > curr_val:
            curr_val = sum(level)
            max_level = curr_level

        curr_level += 1
        
    return max_level
            
print(my_tree)
print("Max Level: ", max_level_sum(my_tree))


    __0__
   /     \
  2       4
 / \     / \
1   5   3   6

Max Level:  3


# 199. Binary Tree Right Side View

Given a binary tree, imagine yourself standing on the right side of it, return the values of the nodes you can see ordered from top to bottom.

In [13]:
def right_side_view(root):
    out = []
    
    if not root:
        return out
    
    queue = [root]
    
    while queue:
        size = len(queue)
        
        for i in range(size):
            curr = queue.pop(0)
            if i == size - 1:
                out.append(curr.value)
                
            if curr.left:
                queue.append(curr.left)
            if curr.right:
                queue.append(curr.right)
                
                
    return out

print(my_tree)
print("Right Side View: ", right_side_view(my_tree))


    __0__
   /     \
  2       4
 / \     / \
1   5   3   6

Right Side View:  [0, 4, 6]


# 103. Binary Tree Zigzag Level Order Traversal

Given a binary tree, return the zigzag level order traversal of its nodes' values. (ie, from left to right, then right to left for the next level and alternate between).

For example:
Given binary tree [3,9,20,null,null,15,7],

In [14]:
def zigzagLevelOrder(root):
    """
    :type root: TreeNode
    :rtype: List[List[int]]
    """
    res = []

    if not root:
        return res

    queue = [root]

    while queue: 
        level = []

        for i in range(len(queue)):
            curr = queue.pop(0)
            if len(res) % 2 == 0:
                level.append(curr.value)
            else:    
                level.insert(0, curr.value)

            if curr.left:
                queue.append(curr.left)
            if curr.right:    
                queue.append(curr.right)

        res.append(level) 

    return res

print(my_tree)
print("Zig-zag level order traversal: ", zigzagLevelOrder(my_tree))


    __0__
   /     \
  2       4
 / \     / \
1   5   3   6

Zig-zag level order traversal:  [[0], [4, 2], [1, 5, 3, 6]]


# General BFS Graph

In [15]:
def bfs_graph(graph):
    if not graph:
        return None
    
    queue = [(0,0)]
    visited = {(0, 0)}
    dirs = [(-1,0), # Left
            (1,0),  # Right
            (0,-1), # Up
            (0,1)]  # Down
    
    while queue:
        print(queue)
        for i in range(len(queue)):
            curr_x, curr_y = queue.pop(0)
            
            for x, y in dirs:
                next_x = curr_x + x
                next_y = curr_y + y
                
                if next_x >= 0 and next_x < len(graph) and \
                    next_y >= 0 and next_y < len(graph[0]) and \
                    (next_x, next_y) not in visited:
                    
                    visited.add((next_x, next_y))
                    queue.append((next_x, next_y))
                    
    return

graph = [[1,2,3],
         [4,5,6],
         [7,8,9]]
                
bfs_graph(graph)

[(0, 0)]
[(1, 0), (0, 1)]
[(2, 0), (1, 1), (0, 2)]
[(2, 1), (1, 2)]
[(2, 2)]


# 1091. Shortest Path in Binary Matrix

In an N by N square grid, each cell is either empty (0) or blocked (1).

A clear path from top-left to bottom-right has length k if and only if it is composed of cells C_1, C_2, ..., C_k such that:

Adjacent cells C_i and C_{i+1} are connected 8-directionally (ie., they are different and share an edge or corner)
C_1 is at location (0, 0) (ie. has value grid[0][0])
C_k is at location (N-1, N-1) (ie. has value grid[N-1][N-1])
If C_i is located at (r, c), then grid[r][c] is empty (ie. grid[r][c] == 0).
Return the length of the shortest such clear path from top-left to bottom-right.  If such a path does not exist, return -1.

In [16]:
def shortest_path_binary_matrix(grid):
    if not grid or grid[0][0] == 1:
        return -1
    
    queue = [(0,0,1)]
    rows = len(grid)
    cols = len(grid[0])
    visited = {(0,0)}
    dirs = [(-1,0),(-1,-1),(1,0),(1,1),(0,1),(1,-1),(0,-1),(-1,-1)]
    
    while queue:
        crow, ccol, d = queue.pop(0)
        
        if (crow, ccol) == (rows - 1, cols - 1):
            return d
        
        for x, y in dirs:
            row = crow + x
            col = ccol + y
            
            if row >= 0 and row < rows and \
                col >= 0 and col < cols and \
                grid[row][col] == 0 and (row, col) not in visited:
                visited.add((row, col))
                queue.append((row, col, d + 1))
    
    
grid = [[0,0,0],
        [1,1,0],
        [1,1,0]]
print(np.matrix(grid))
print("Shortest Path from top-left to bottom-right: ", shortest_path_binary_matrix(grid))

[[0 0 0]
 [1 1 0]
 [1 1 0]]
Shortest Path from top-left to bottom-right:  4


# 286. Walls and Gates

You are given a m x n 2D grid initialized with these three possible values.

-1 - A wall or an obstacle.
0 - A gate.
INF - Infinity means an empty room. We use the value 231 - 1 = 2147483647 to represent INF as you may assume that the distance to a gate is less than 2147483647.
Fill each empty room with the distance to its nearest gate. If it is impossible to reach a gate, it should be filled with INF.

In [21]:
def wallsAndGates(rooms):
    if not rooms:
        return None
    
    queue = []
    dirs = [(-1,0), (1,0), (0,-1), (0,1)] # Directions we can traverse
    rows = len(rooms)
    cols = len(rooms[0])
    INF = 2147483647 # Empty room
    dist = 1 # Starting distance from each gate
    
    # Find all gates and perform BFS to find each rooms closest gate
    for i in range(rows):
        for j in range(cols):
            if rooms[i][j] == 0:
                queue.append((i, j))
                
    # Perform BFS on all gates
    while queue:
        size = len(queue)
        
        for i in range(size):
            x, y = queue.pop(0)
            
            for i, j in dirs:
                row = x + i
                col = y + j
                
                if row >= 0 and row < rows and col >= 0 and col < cols and rooms[row][col] == INF:
                    queue.append((row, col))
                    rooms[row][col] = dist
                    
        dist += 1
        
        
rooms = [[2147483647,-1,0,2147483647],[2147483647,2147483647,2147483647,-1],[2147483647,-1,2147483647,-1],[0,-1,2147483647,2147483647]]
print(np.array(rooms))
wallsAndGates(rooms)
print("Find each rooms nearest gate: \n", np.array(rooms))

[[2147483647         -1          0 2147483647]
 [2147483647 2147483647 2147483647         -1]
 [2147483647         -1 2147483647         -1]
 [         0         -1 2147483647 2147483647]]
Find each rooms nearest gate: 
 [[ 3 -1  0  1]
 [ 2  2  1 -1]
 [ 1 -1  2 -1]
 [ 0 -1  3  4]]


# 994. Rotting Oranges

In a given grid, each cell can have one of three values:

the value 0 representing an empty cell;
the value 1 representing a fresh orange;
the value 2 representing a rotten orange.
Every minute, any fresh orange that is adjacent (4-directionally) to a rotten orange becomes rotten.

Return the minimum number of minutes that must elapse until no cell has a fresh orange.  If this is impossible, return -1 instead.

In [22]:
def orangesRotting(grid):
    """
    :type grid: List[List[int]]
    :rtype: int
    """
    if not grid:
        return -1

    q = []
    visited = set()
    dirs = [(-1,0), (1,0), (0,-1), (0,1)]
    rows = len(grid)
    cols = len(grid[0])
    fresh_count = 0
    minutes = 0

    for i in range(rows):
        for j in range(cols):
            if grid[i][j] == 2:
                q.append((i, j))
                visited.add((i, j))
            elif grid[i][j] == 1:
                fresh_count += 1

    if fresh_count == 0:
        return 0

    while q:
        size = len(q)
        for i in range(size):
            curr = q.pop(0)

            for dir in dirs:
                row = curr[0] + dir[0]
                col = curr[1] + dir[1]


                if row < rows and row >= 0 and \
                    col < cols and col >= 0 and \
                    grid[row][col] == 1 and (row, col) not in visited:
                    q.append((row, col))
                    visited.add((row, col))
                    fresh_count -= 1

        minutes += 1

    if fresh_count == 0:    
        return minutes - 1

    return -1

grid = [[2,1,1],
        [1,1,0],
        [0,1,1]]
print(np.matrix(grid))
print("Number of minutes for all oranges to become rotten: ", orangesRotting(grid))

[[2 1 1]
 [1 1 0]
 [0 1 1]]
Number of minutes for all oranges to become rotten:  4
