In [6]:
from binarytree import tree
import collections
import numpy as np

In [7]:
my_tree = tree(height=2, is_perfect=True)
print(my_tree)


    __5__
   /     \
  2       3
 / \     / \
6   1   0   4



## There are two types of BFS questions:
* Tree
* Graph

# Appendix

## Array

* [1306. Jump Game III](#1306.-Jump-Game-III) ⭐️

## Tree

* [101. Symmetric Tree](#101.-Symmetric-Tree)

* [102. Binary Level Order Traversal](#102.-Binary-Level-Order-Traversal)

* [103. Binary Tree Zigzag Level Order Traversal](#103.-Binary-Tree-Zigzag-Level-Order-Traversal)

* [107. Binary Tree Level Order Traversal II](#107.-Binary-Tree-Level-Order-Traversal-II)

* [111. Minimum Depth of Binary Tree](#111.-Minimum-Depth-of-Binary-Tree)

* [199. Binary Tree Right Side View](#199.-Binary-Tree-Right-Side-View)

* [513. Find Bottom Left Tree Value](#513.-Find-Bottom-Left-Tree-Value)

* [515. Find Largest Value in Each Tree Row](#515.-Find-Largest-Value-in-Each-Tree-Row)

* [965. Univalued Binary Tree](#965.-Univalued-Binary-Tree)

* [993. Cousins in Binary Tree](#993.-Cousins-in-Binary-Tree)

* [1161. Maximum Level of a Binary Tree](#1161.-Maximum-Level-of-a-Binary-Tree)

* [1302. Deepest Leaves Sum](#1302.-Deepest-Leaves-Sum)

* [1315. Sum of Nodes with Even-Valued Grandparent](#1315.-Sum-of-Nodes-with-Even-Valued-Grandparent)

### Tree + HashMap

* [314. Binary Tree Vertical Order Traversal](#314.-Binary-Tree-Vertical-Order-Traversal)

## N-ary Tree

* [429. N-ary Tree Level Order Traversal](#429.-N-ary-Tree-Level-Order-Traversal)

* [559. Maximum Depth of N-ary Tree](#559.-Maximum-Depth-of-N-ary-Tree)


## Graph

* [200. Number of Islands](#200.-Number-of-Islands)

* [286. Walls and Gates](#286.-Walls-and-Gates)

* [542. 01 Matrix](#542.-01-Matrix)

* [863. All Nodes Distance K in Binary Tree](#863.-All-Nodes-Distance-K-in-Binary-Tree)

* [934. Shortest Bridge](#934.-Shortest-Bridge)

* [994. Rotting Oranges](#994.-Rotting-Oranges)

* [1091. Shortest Path in Binary Matrix](#1091.-Shortest-Path-in-Binary-Matrix)

* [1162. As Far from Land as Possible](#1162.-As-Far-from-Land-as-Possible)

* [1197. Minimum Knight Moves](#1197.-Minimum-Knight-Moves)

## Adjacency List

* [261. Graph Valid Tree](#261.-Graph-Valid-Tree)

## Uncategorized Yet

* [127. Word Ladder](#127.-Word-Ladder)

* [279. Perfect Squares](#279.-Perfect-Squares)


# Array

# 1306. Jump Game III

This is an interesting one. Since we can move left or right in this array, we can treat this as building up a decision tree where we can move one step at a time. This sounds a lot like BFS.

Idea:

* Use BFS to build a tree of positions of where we can jump to
* Use a set to record indexes of positions we have visted.
* If we come across a index in the set, that means we're going to end up in a loop.
* If we've visited all places we can go, it's not possible to find our target 0



In [8]:
class Solution:
    def canReach(self, arr, start: int) -> bool:
        if not arr:
            return False
        
        q = [start]
        n = len(arr)
        visited = {start}
        
        while q:
            print(q)
            index = q.pop(0)
            if arr[index] == 0:
                return True
            
            left = index - arr[index]
            right = index + arr[index]
            
            if left >= 0 and left not in visited:
                q.append(left)
                visited.add(left)
            if right < n and right not in visited:    
                q.append(right)
                visited.add(right)
                
        return False        

In [9]:
arr = [4,2,3,0,3,1,2]
start = 5

Solution().canReach(arr, start)

[5]
[4, 6]
[6, 1]
[1]
[3]


True

# N-ary Breadth First Search

In [10]:
def n_ary_bfs(root):
    output = []
    
    if not root:
        return output
    
    queue = [root]
    
    while queue:
        curr = queue.pop(0)
        output.append(curr.value)
        
        for child in curr.children:
            queue.append(child)
            
    return output

# 429. N-ary Tree Level Order Traversal

In [11]:
def levelOrder(root):
    out = []

    if not root:
        return out

    queue = [root]

    while queue:
        level = []

        for i in range(len(queue)):
            curr = queue.pop(0)
            level.append(curr.val)

            for child in curr.children:
                queue.append(child)

        out.append(level)

    return out

# 559. Maximum Depth of N-ary Tree

In [12]:
def maxDepth(root):
    """
    :type root: Node
    :rtype: int
    """
    max_depth = 0

    if not root:
        return max_depth

    queue = [root] 

    while queue:
        for i in range(len(queue)):
            curr = queue.pop(0)

            for child in curr.children:
                queue.append(child)

        max_depth += 1

    return max_depth

# General Breadth First Search

In [13]:
def bfs(root):
    output = []
    
    if not root:
        return output
    
    queue = [root]
    
    while queue:
        curr = queue.pop(0)
        output.append(curr.value)
        
        if curr.left:
            queue.append(curr.left)
        if curr.right:
            queue.append(curr.right)
            
    return output

print(my_tree)
print("BFS: ", bfs(my_tree))


    __5__
   /     \
  2       3
 / \     / \
6   1   0   4

BFS:  [5, 2, 3, 6, 1, 0, 4]


# 101. Symmetric Tree

Given a binary tree, check whether it is a mirror of itself (ie, symmetric around its center).

For example, this binary tree [1,2,2,3,4,4,3] is symmetric:

In [14]:
def isSymmetric(root):
    """
    :type root: TreeNode
    :rtype: bool
    """
    if not root:
        return True

    queue = [(root.left, root.right)]

    while queue:
        size = len(queue)

        for i in range(size):
            left, right = queue.pop(0)

            if not left and not right:
                continue
            elif not left or not right:
                return False
            elif left.value != right.value:
                return False

            queue.append((left.left, right.right))
            queue.append((left.right, right.left))

    return True

print(my_tree)
print("Is the tree symmetric: ", isSymmetric(my_tree))


    __5__
   /     \
  2       3
 / \     / \
6   1   0   4

Is the tree symmetric:  False


# 102. Binary Level Order Traversal

Given a binary tree, return the level order traversal of its nodes' values. (ie, from left to right, level by level).

In [15]:
def level_order_traversal(root):
    output = []
    
    if not root:
        return output
    
    queue = [root]
    
    while queue:
        level = []
        for i in range(len(queue)):
            curr = queue.pop(0)
            level.append(curr.value)
            
            if curr.left:
                queue.append(curr.left)
            if curr.right:
                queue.append(curr.right)
                
        output.append(level)
        
    return output

print(my_tree)
print("Levels: ", level_order_traversal(my_tree))


    __5__
   /     \
  2       3
 / \     / \
6   1   0   4

Levels:  [[5], [2, 3], [6, 1, 0, 4]]


# 103. Binary Tree Zigzag Level Order Traversal

Given a binary tree, return the zigzag level order traversal of its nodes' values. (ie, from left to right, then right to left for the next level and alternate between).

For example:
Given binary tree [3,9,20,null,null,15,7],

In [16]:
def zigzagLevelOrder(root):
    """
    :type root: TreeNode
    :rtype: List[List[int]]
    """
    res = []

    if not root:
        return res

    queue = [root]

    while queue: 
        level = []

        for i in range(len(queue)):
            curr = queue.pop(0)
            if len(res) % 2 == 0:
                level.append(curr.value)
            else:    
                level.insert(0, curr.value)

            if curr.left:
                queue.append(curr.left)
            if curr.right:    
                queue.append(curr.right)

        res.append(level) 

    return res

print(my_tree)
print("Zig-zag level order traversal: ", zigzagLevelOrder(my_tree))


    __5__
   /     \
  2       3
 / \     / \
6   1   0   4

Zig-zag level order traversal:  [[5], [3, 2], [6, 1, 0, 4]]


# 107. Binary Tree Level Order Traversal II

Given a binary tree, return the bottom-up level order traversal of its nodes' values. (ie, from left to right, level by level from leaf to root).

In [17]:
def level_order_bottom(root):
    output = []
    
    if not root:
        return output
    
    queue = [root]
    
    while queue:
        level = []
        for i in range(len(queue)):
            curr = queue.pop(0)
            level.append(curr.value)
            
            if curr.left:
                queue.append(curr.left)
            if curr.right:
                queue.append(curr.right)
                
        output.insert(0, level)
            
    return output

print(my_tree)
print("Reverse Levels: ", level_order_bottom(my_tree))


    __5__
   /     \
  2       3
 / \     / \
6   1   0   4

Reverse Levels:  [[6, 1, 0, 4], [2, 3], [5]]


# 111. Minimum Depth of Binary Tree

In [18]:
def minDepth(root):
    """
    :type root: TreeNode
    :rtype: int
    """
    if not root:
        return 0

    min_depth = 1
    queue = [root]

    while queue:
        for i in range(len(queue)):
            curr = queue.pop(0)

            if not curr.left and not curr.right:
                return min_depth

            if curr.left:
                queue.append(curr.left)
            if curr.right:    
                queue.append(curr.right)

        min_depth += 1

    return min_depth

print(my_tree)
print("Min depth of binary tree: ", minDepth(my_tree))


    __5__
   /     \
  2       3
 / \     / \
6   1   0   4

Min depth of binary tree:  3


# 199. Binary Tree Right Side View

Given a binary tree, imagine yourself standing on the right side of it, return the values of the nodes you can see ordered from top to bottom.

In [19]:
def right_side_view(root):
    out = []
    
    if not root:
        return out
    
    queue = [root]
    
    while queue:
        size = len(queue)
        
        for i in range(size):
            curr = queue.pop(0)
            if i == size - 1:
                out.append(curr.value)
                
            if curr.left:
                queue.append(curr.left)
            if curr.right:
                queue.append(curr.right)
                
                
    return out

print(my_tree)
print("Right Side View: ", right_side_view(my_tree))


    __5__
   /     \
  2       3
 / \     / \
6   1   0   4

Right Side View:  [5, 3, 4]


# 314. Binary Tree Vertical Order Traversal

Time: `O(nlogn)`

* We need to traverse all of the nodes in the tree `O(n)` and we also need to sort the keys `O(nlogn)`

Space: `O(n)?`

* We might have to store all of the tree nodes as keys in our dictionary

In [20]:
class Solution:
    def verticalOrder(self, root):
        if not root:
            return None
        
        queue = [[root, 0]]
        cols = {}
        res = []
        
        while queue:
            for i in range(len(queue)):
                node, col = queue.pop(0)
                
                if col not in cols:
                    cols[col] = []
                    
                cols[col].append(node.value)
                
                if node.left:
                    queue.append([node.left, col - 1])
                if node.right:
                    queue.append([node.right, col + 1])
                    
        sortedCols = sorted([col for col in cols])
        for col in sortedCols:
            res.append(cols[col])
            
        return res

s = Solution()
print(s.verticalOrder(my_tree))
print(my_tree)

[[6], [2], [5, 1, 0], [3], [4]]

    __5__
   /     \
  2       3
 / \     / \
6   1   0   4



Time: `O(n)`

* We can optimize the solution by not sorting the keys when iterating through the dictionary.
* Instead, we can keep track of the left-most column and the right-most column which are represented by the negative and postive numbers

Space: `O(n)`

In [21]:
class Solution2:
    def verticalOrder(self, root):
        if not root:
            return None
        
        queue = [[root, 0]]
        cols = {}
        res = []
        maxCol = 0
        minCol = 0
        
        while queue:
            for _ in range(len(queue)):
                node, col = queue.pop(0)
                
                if col not in cols:
                    cols[col] = []
                    
                cols[col].append(node.value)
                maxCol = max(maxCol, col)
                minCol = min(minCol, col)
                
                if node.left:
                    queue.append([node.left, col - 1])
                if node.right:
                    queue.append([node.right, col + 1])
                    
        for col in range(minCol, maxCol + 1):
            res.append(cols[col])
            
        return res

s = Solution2()
print(s.verticalOrder(my_tree))
print(my_tree)

[[6], [2], [5, 1, 0], [3], [4]]

    __5__
   /     \
  2       3
 / \     / \
6   1   0   4



# 513. Find Bottom Left Tree Value

Given a binary tree, find the leftmost value in the last row of the tree.

In [22]:
def find_bottom_left_value(root):
    if not root:
        return None
    
    queue = [root]
    
    while queue:
        curr = queue.pop(0)
        
        if curr.right:
            queue.append(curr.right)
        if curr.left:
            queue.append(curr.left)
            
    return curr.value

print(my_tree)
print("Bottom Left Value: ", find_bottom_left_value(my_tree))


    __5__
   /     \
  2       3
 / \     / \
6   1   0   4

Bottom Left Value:  6


# 515. Find Largest Value in Each Tree Row

In [23]:
def largestValues(root):
    out = []

    if not root:
        return out

    queue = [root]
    biggest = -float('inf')
    biggestSoFar = -float('inf')

    while queue:
        size = len(queue)

        for i in range(size):
            curr = queue.pop(0)
            biggestSoFar = curr.value

            if curr.left:
                queue.append(curr.left)
            if curr.right:
                queue.append(curr.right)

            biggest = max(biggest, biggestSoFar)


        out.append(biggest)
        biggest = -float('inf')
        biggestSoFar = -float('inf')

    return out

print(my_tree)
print(largestValues(my_tree))


    __5__
   /     \
  2       3
 / \     / \
6   1   0   4

[5, 3, 6]


# 965. Univalued Binary Tree

A binary tree is univalued if every node in the tree has the same value.

Return true if and only if the given tree is univalued.

## Idea:

We can use the root's value to compare to every other node in the tree that we traverse. If there is such a node which is not equal to the root's value, we know that all nodes in the tree cannot be the same.

Use level-order traversal to check all nodes are the same.


## Complexity:

**Time**: O(n)

We must visit every node in this binary tree to check if all values are the same which is O(n)

**Space**: O(n)

Using BFS, the data structure, queue, can hold at most n/2 nodes at the bottom of a full tree.

So at lowest level, we store n/2 nodes which becomes O(n)

In [24]:
class Solution(object):
    def isUnivalTree(self, root):
        """
        :type root: TreeNode
        :rtype: bool
        """
        if not root:
            return True
        
        queue = [root]
        v = root.value
        
        while queue:
            curr = queue.pop(0)
            if curr.value != v:
                return False
            
            if curr.left:
                queue.append(curr.left)
            if curr.right:
                queue.append(curr.right)
                
        return True
    
print(my_tree)
print("Are all values in the tree the same?: ", Solution().isUnivalTree(my_tree))


    __5__
   /     \
  2       3
 / \     / \
6   1   0   4

Are all values in the tree the same?:  False


# 993. Cousins in Binary Tree

In a binary tree, the root node is at depth 0, and children of each depth k node are at depth k+1.

Two nodes of a binary tree are cousins if they have the same depth, but have different parents.

We are given the root of a binary tree with unique values, and the values x and y of two different nodes in the tree.

Return true if and only if the nodes corresponding to the values x and y are cousins.

**Time:** O(n)

**Space:** O(log(n))

**Idea:**

* We need to check that both nodes are in the same level but not have the same parent.
* Have two flags that check if we have found both nodes on the same level.
* Also have a check that if we found x, y with the same parent, return False

In [25]:
def isCousins(root, x, y) -> bool:
    q = [root]
    
    while q:
        
        a = False
        b = False
        
        for i in range(len(q)):
            curr = q.pop(0)
            
            if curr.value == x:
                a = True
            if curr.value == y:
                b = True
                
            if curr.left and curr.right:
                if curr.left.value == x and curr.right.value == y:
                    return False
                if curr.right.value == x and curr.left.value == y:
                    return False
                
            if curr.left:
                q.append(curr.left)
            if curr.right:
                q.append(curr.right)
                
        if a and b:
            return True
    
    return False

print(my_tree)
print("Are these two nodes cousins: ", isCousins(my_tree, 6, 2))


    __5__
   /     \
  2       3
 / \     / \
6   1   0   4

Are these two nodes cousins:  False


# 1161. Maximum Level of a Binary Tree

Given the root of a binary tree, the level of its root is 1, the level of its children is 2, and so on.

Return the smallest level X such that the sum of all the values of nodes at level X is maximal.

In [26]:
def max_level_sum(root):
    if not root:
        return None

    max_level = 1
    curr_level = 1
    curr_val = -float('inf')

    queue = [root]

    while queue:
        level = []
        for i in range(len(queue)):
            curr = queue.pop(0)
            level.append(curr.value)

            if curr.left:
                queue.append(curr.left)
            if curr.right:
                queue.append(curr.right)

        if sum(level) > curr_val:
            curr_val = sum(level)
            max_level = curr_level

        curr_level += 1
        
    return max_level
            
print(my_tree)
print("Max Level: ", max_level_sum(my_tree))


    __5__
   /     \
  2       3
 / \     / \
6   1   0   4

Max Level:  3


# 1302. Deepest Leaves Sum

Idea:

Time: O(n) We have to visit every node in the tree

Space: O(logn) Our level array contains at most logn nodes which is the size of the bottom of a perfect binary tree

* We want to find the sum of the deepest leaves in the tree.
* Let's traverse the tree level by level.
* By doing so, we can find the sum of each level's leaves
* A leaf is a node which does not have any left or right pointers (children)

In [27]:
class TreeNode:
    def __init__(self, x):
        self.val = x
        self.left = None
        self.right = None

class Solution:
    def deepestLeavesSum(self, root: TreeNode) -> int:
        if not root:
            return 0
        
        q = [root]
        s = 0
        res = []
        
        while q: 
            level = []
            
            for i in range(len(q)):
                curr = q.pop(0)
                level.append(curr.val)
                
                if curr.left:
                    q.append(curr.left)
                if curr.right:    
                    q.append(curr.right)
                    
            res.append(level)        
            s = sum(level)
            
        return s
                    

# 1315. Sum of Nodes with Even-Valued Grandparent

**Solution 1: BFS**

Time: `O(n)` - We need to traverse the entire tree

Space: `O(n)` - We might have to store all the elements in the tree. This is greater than the queue of the BFS that we are storing the levels on

In [30]:
class Solution:
    def sumEvenGrandparent(self, root) -> int:
        sum = 0
        
        if not root:
            return sum
        
        # curr, parent, grandparent
        queue = [[root, None, None]]
        
        while queue:
            for _ in range(len(queue)):
                curr, parent, gp = queue.pop(0)
                
                if gp and gp.value % 2 == 0:
                    sum += curr.value
                    
                if curr.left:
                    queue.append([curr.left, curr, parent])
                if curr.right:
                    queue.append([curr.right, curr, parent])
                    
        return sum
    
s = Solution()
print(my_tree)
print(s.sumEvenGrandparent(my_tree))


    __5__
   /     \
  2       3
 / \     / \
6   1   0   4

0


# General BFS Graph

In [21]:
def bfs_graph(graph):
    if not graph:
        return None
    
    queue = [(0,0)]
    visited = {(0, 0)}
    dirs = [(-1,0), # Left
            (1,0),  # Right
            (0,-1), # Up
            (0,1)]  # Down
    
    while queue:
        print(queue)
        for i in range(len(queue)):
            curr_x, curr_y = queue.pop(0)
            
            for x, y in dirs:
                next_x = curr_x + x
                next_y = curr_y + y
                
                if next_x >= 0 and next_x < len(graph) and \
                    next_y >= 0 and next_y < len(graph[0]) and \
                    (next_x, next_y) not in visited:
                    
                    visited.add((next_x, next_y))
                    queue.append((next_x, next_y))
                    
    return

graph = [[1,2,3],
         [4,5,6],
         [7,8,9]]
                
bfs_graph(graph)

[(0, 0)]
[(1, 0), (0, 1)]
[(2, 0), (1, 1), (0, 2)]
[(2, 1), (1, 2)]
[(2, 2)]


# 200. Number of Islands

In [22]:
def bfs(grid, row, col):
    dirs = [(-1,0), (1,0), (0,-1), (0,1)]
    queue = [(row, col)]

    while queue:
        i, j = queue.pop(0)

        for x, y in dirs:
            nrow = x + i
            ncol = y + j

            if nrow >= 0 and nrow < len(grid) and \
                ncol >= 0 and ncol < len(grid[0]) and \
                grid[nrow][ncol] == '1':
                grid[nrow][ncol] = '0'
                queue.append((nrow, ncol))

    return


def numIslands(grid):
    """
    :type grid: List[List[str]]
    :rtype: int
    """
    if not grid:
        return 0

    islands = 0
    rows = len(grid)
    cols = len(grid[0])

    for i in range(rows):
        for j in range(cols):
            if grid[i][j] == '1':
                bfs(grid, i, j)
                islands += 1

    return islands

grid = [["1","1","1","1","0"],["1","1","0","1","0"],["1","1","0","0","0"],["0","0","0","0","0"]]
print(np.array(grid))
print('Number of Islands: ', numIslands(grid))

[['1' '1' '1' '1' '0']
 ['1' '1' '0' '1' '0']
 ['1' '1' '0' '0' '0']
 ['0' '0' '0' '0' '0']]
Number of Islands:  1


# 286. Walls and Gates

You are given a m x n 2D grid initialized with these three possible values.

-1 - A wall or an obstacle.
0 - A gate.
INF - Infinity means an empty room. We use the value 231 - 1 = 2147483647 to represent INF as you may assume that the distance to a gate is less than 2147483647.
Fill each empty room with the distance to its nearest gate. If it is impossible to reach a gate, it should be filled with INF.

In [23]:
def wallsAndGates(rooms):
    if not rooms:
        return None
    
    queue = []
    dirs = [(-1,0), (1,0), (0,-1), (0,1)] # Directions we can traverse
    rows = len(rooms)
    cols = len(rooms[0])
    INF = 2147483647 # Empty room
    dist = 1 # Starting distance from each gate
    
    # Find all gates and perform BFS to find each rooms closest gate
    for i in range(rows):
        for j in range(cols):
            if rooms[i][j] == 0:
                queue.append((i, j))
                
    # Perform BFS on all gates
    while queue:
        size = len(queue)
        
        for i in range(size):
            x, y = queue.pop(0)
            
            for i, j in dirs:
                row = x + i
                col = y + j
                
                if row >= 0 and row < rows and \
                    col >= 0 and col < cols and \
                    rooms[row][col] == INF:
                    
                    queue.append((row, col))
                    rooms[row][col] = dist
                    
        dist += 1
        
        
rooms = [[2147483647,-1,0,2147483647],[2147483647,2147483647,2147483647,-1],[2147483647,-1,2147483647,-1],[0,-1,2147483647,2147483647]]
print(np.array(rooms))
wallsAndGates(rooms)
print("Find each rooms nearest gate: \n", np.array(rooms))

[[2147483647         -1          0 2147483647]
 [2147483647 2147483647 2147483647         -1]
 [2147483647         -1 2147483647         -1]
 [         0         -1 2147483647 2147483647]]
Find each rooms nearest gate: 
 [[ 3 -1  0  1]
 [ 2  2  1 -1]
 [ 1 -1  2 -1]
 [ 0 -1  3  4]]


# 542. 01 Matrix

Given a matrix consists of 0 and 1, find the distance of the nearest 0 for each cell.

The distance between two adjacent cells is 1.



In [24]:
class Solution(object):
    def updateMatrix(self, m):
        """
        :type matrix: List[List[int]]
        :rtype: List[List[int]]
        """
        
        queue = []
        visited = set()
        rows = len(m)
        cols = len(m[0])
        dirs = [(-1,0), (0,1), (1,0), (0,-1)]
        
        for i in range(rows):
            for j in range(cols):
                if m[i][j] == 0:
                    queue.append((i, j))
                    visited.add((i, j))
                    
        dist = 1            
        
        while queue:
            size = len(queue)
            
            for _ in range(size):
                x, y = queue.pop(0)
                
                for i, j in dirs:
                    row = x + i
                    col = y + j
                    
                    if row >= 0 and row < rows and \
                        col >= 0 and col < cols and \
                        (row, col) not in visited:
                        
                        m[row][col] = dist
                        queue.append((row, col))
                        visited.add((row, col))
                        
            dist += 1
                        
        return m
    
grid = [[0,0,0],
 [0,1,0],
 [1,1,1]]
print(np.array(grid))

solution = Solution().updateMatrix(grid)
print("Shortest distance from 1 to 0: \n", np.array(solution))

[[0 0 0]
 [0 1 0]
 [1 1 1]]
Shortest distance from 1 to 0: 
 [[0 0 0]
 [0 1 0]
 [1 2 1]]


# 863. All Nodes Distance K in Binary Tree


We are given a binary tree (with root node root), a target node, and an integer value K.

Return a list of the values of all nodes that have a distance K from the target node.  The answer can be returned in any order.

* Main Idea: Be able to turn a tree, which is a directed graph, into a graph.
* Hashmap to store the child's parent.
* BFS

In [25]:
def distanceK(root, target, K):
    
    dic = dict()
    helper(dic, root, None)
    
    q = [target]
    seen = {target}
    dist = 0
    res = []
    
    while q:
        for i in range(len(q)):
            curr = q.pop(0)
            if dist == K:
                res.append(curr.val)
                
            if curr.left and curr.left not in seen:
                seen.add(curr.left)
                q.append(curr.left)
            if curr.right and curr.right not in seen:
                seen.add(curr.right)
                q.append(curr.right)
            if dic[curr] and dic[curr] not in seen:
                seen.add(dic[curr])
                q.append(dic[curr])
        
        dist += 1
        
    return res
    
def helper(dic, root, parent):
    if not root:
        return
    
    helper(dic, root.left, root)
    helper(dic, root.right, root)

# 934. Shortest Bridge

In a given 2D binary array A, there are two islands.  (An island is a 4-directionally connected group of 1s not connected to any other 1s.)

Now, we may change 0s to 1s so as to connect the two islands together to form 1 island.

Return the smallest number of 0s that must be flipped.  (It is guaranteed that the answer is at least 1.)

In [26]:
class Solution(object):
    def dfs(self, grid, i, j, rows, cols, queue, visited, dirs):
        if i < 0 or i >= rows or j < 0 or j >= cols or grid[i][j] == 0 or (i, j) in visited:
            return
        
        visited.add((i, j))
        queue.append((i, j))
        
        for x, y in dirs:
            row = i + x
            col = j + y
            
            self.dfs(grid, row, col, rows, cols, queue, visited, dirs)
            
        
    def shortestBridge(self, A):
        """
        :type A: List[List[int]]
        :rtype: int
        """
        queue = []
        visited = set()
        dirs = [(-1,0), (1,0), (0,-1), (0,1)]
        rows = len(A)
        cols = len(A[0])
        flips = 0
        is_found = False
        
        # Find the first island and mark it as found and add it to the queue
        for i in range(rows):
            if is_found:
                break;
                
            for j in range(cols):
                if A[i][j] == 1 and (i, j) not in visited:
                    self.dfs(A, i, j, rows, cols, queue, visited, dirs)
                    is_found = True
                    break;
                    
                    
        # Find the shortest path from the island to the next island            
        while queue:
            size = len(queue)
            
            for z in range(size):
                x, y = queue.pop(0)
                
                for i, j in dirs:
                    row = x + i
                    col = j + y
                    
                    if row >= 0 and row < rows and \
                        col >= 0 and col < cols and \
                        (row, col) not in visited:
                        
                        if A[row][col] == 1:
                            return flips
                        
                        visited.add((row, col))
                        queue.append((row, col))
                        
            flips += 1
            
            
        return -1
      
grid = [[1,1,1,1,1],[1,0,0,0,1],[1,0,1,0,1],[1,0,0,0,1],[1,1,1,1,1]]
print(np.array(grid))
print("Min number of flips: ", Solution().shortestBridge(grid))

[[1 1 1 1 1]
 [1 0 0 0 1]
 [1 0 1 0 1]
 [1 0 0 0 1]
 [1 1 1 1 1]]
Min number of flips:  1


# 994. Rotting Oranges

In a given grid, each cell can have one of three values:

the value 0 representing an empty cell;
the value 1 representing a fresh orange;
the value 2 representing a rotten orange.
Every minute, any fresh orange that is adjacent (4-directionally) to a rotten orange becomes rotten.

Return the minimum number of minutes that must elapse until no cell has a fresh orange.  If this is impossible, return -1 instead.

In [27]:
def orangesRotting(grid):
    """
    :type grid: List[List[int]]
    :rtype: int
    """
    if not grid:
        return -1

    q = []
    visited = set()
    dirs = [(-1,0), (1,0), (0,-1), (0,1)]
    rows = len(grid)
    cols = len(grid[0])
    fresh_count = 0
    minutes = 0

    for i in range(rows):
        for j in range(cols):
            if grid[i][j] == 2:
                q.append((i, j))
                visited.add((i, j))
            elif grid[i][j] == 1:
                fresh_count += 1

    if fresh_count == 0:
        return 0

    while q:
        size = len(q)
        for i in range(size):
            curr = q.pop(0)

            for dir in dirs:
                row = curr[0] + dir[0]
                col = curr[1] + dir[1]


                if row < rows and row >= 0 and \
                    col < cols and col >= 0 and \
                    grid[row][col] == 1 and (row, col) not in visited:
                    q.append((row, col))
                    visited.add((row, col))
                    fresh_count -= 1

        minutes += 1

    if fresh_count == 0:    
        return minutes - 1

    return -1

grid = [[2,1,1],
        [1,1,0],
        [0,1,1]]
print(np.matrix(grid))
print("Number of minutes for all oranges to become rotten: ", orangesRotting(grid))

[[2 1 1]
 [1 1 0]
 [0 1 1]]
Number of minutes for all oranges to become rotten:  4


# 1091. Shortest Path in Binary Matrix

In an N by N square grid, each cell is either empty (0) or blocked (1).

A clear path from top-left to bottom-right has length k if and only if it is composed of cells C_1, C_2, ..., C_k such that:

Adjacent cells C_i and C_{i+1} are connected 8-directionally (ie., they are different and share an edge or corner)
C_1 is at location (0, 0) (ie. has value grid[0][0])
C_k is at location (N-1, N-1) (ie. has value grid[N-1][N-1])
If C_i is located at (r, c), then grid[r][c] is empty (ie. grid[r][c] == 0).
Return the length of the shortest such clear path from top-left to bottom-right.  If such a path does not exist, return -1.

In [28]:
def shortest_path_binary_matrix(grid):
    if not grid or grid[0][0] == 1:
        return -1
    
    queue = [(0,0,1)]
    rows = len(grid)
    cols = len(grid[0])
    visited = {(0,0)}
    dirs = [(-1,0),(-1,-1),(1,0),(1,1),(0,1),(1,-1),(0,-1),(-1,-1)]
    
    while queue:
        crow, ccol, d = queue.pop(0)
        
        if (crow, ccol) == (rows - 1, cols - 1):
            return d
        
        for x, y in dirs:
            row = crow + x
            col = ccol + y
            
            if row >= 0 and row < rows and \
                col >= 0 and col < cols and \
                grid[row][col] == 0 and (row, col) not in visited:
                visited.add((row, col))
                queue.append((row, col, d + 1))
    
    
grid = [[0,0,0],
        [1,1,0],
        [1,1,0]]
print(np.matrix(grid))
print("Shortest Path from top-left to bottom-right: ", shortest_path_binary_matrix(grid))

[[0 0 0]
 [1 1 0]
 [1 1 0]]
Shortest Path from top-left to bottom-right:  4


# 1162. As Far from Land as Possible

Given an N x N grid containing only values 0 and 1, where 0 represents water and 1 represents land, find a water cell such that its distance to the nearest land cell is maximized and return the distance.

The distance used in this problem is the Manhattan distance: the distance between two cells (x0, y0) and (x1, y1) is |x0 - x1| + |y0 - y1|.

If no land or water exists in the grid, return -1.

In [29]:
class Solution(object):
    def maxDistance(self, grid):
        """
        :type grid: List[List[int]]
        :rtype: int
        """
        queue = []
        visited = set()            
        rows = len(grid)
        cols = len(grid[0])
        dirs = [(-1,0), (1,0), (0,-1), (0,1)]
        dist = 0
        water = 0
        
        for i in range(rows):
            for j in range(cols):
                if grid[i][j] == 1:
                    queue.append((i, j))
                elif grid[i][j] == 0:
                    water += 1
                    
        if not water:
            return -1
                    
        while queue:
            size = len(queue)
            
            for v in range(size):
                x, y = queue.pop(0)
                
                for i, j in dirs:
                    row = x + i
                    col = y + j
                    
                    if row >= 0 and row < rows and \
                        col >= 0 and col < cols and \
                        grid[row][col] == 0 and (row, col) not in visited:
                        visited.add((row, col))
                        queue.append((row, col))
                        
            dist += 1
            
        return dist - 1
    
grid = [[1,0,0],[0,0,0],[0,0,0]]
print(np.array(grid))
print("Max distance from land to water: ", Solution().maxDistance(grid))

[[1 0 0]
 [0 0 0]
 [0 0 0]]
Max distance from land to water:  4


# 1197. Minimum Knight Moves

In an infinite chess board with coordinates from -infinity to +infinity, you have a knight at square [0, 0].

A knight has 8 possible moves it can make, as illustrated below. Each move is two squares in a cardinal direction, then one square in an orthogonal direction.

In [30]:
class Solution(object):
    def minKnightMoves(self, x, y):
        """
        :type x: int
        :type y: int
        :rtype: int
        """
        queue = [(0,0)]
        dirs = [(-2,1), (-1,2), (1,2), (2,1), (2,-1), (1,-2), (-1,-2), (-2,-1)]
        visited = {(0,0)}
        moves = 1
        
        # There are four quadrants on the board, if we take the abs value
        # of the location, we can only search 1 quadrant instead of four
        x = abs(x)
        y = abs(y)
        
        if (x, y) == (0, 0):
            return 0
        
        while queue:
            size = len(queue)
            
            for _ in range(size):
                a, b = queue.pop(0)
                
                for i, j in dirs:
                    row = a + i
                    col = b + j
                    
                    # Since we have limited the target location to being
                    # only positive, prevent our moves from leaving the first
                    # quadrant and becoming in negative positions.
                    if (row, col) not in visited and row > -2 and col > -2:
                        if (row, col) == (x, y):
                            return moves
                        
                        visited.add((row, col))
                        queue.append((row, col))
                        
            moves += 1
        
x = 5
y = 5

s = Solution().minKnightMoves(x, y)
print("Min Knight moves to square: ", s)

Min Knight moves to square:  4


In [31]:
print(my_tree)


    __2__
   /     \
  6       4
 / \     / \
1   5   0   3



# Adjacency List

Given n nodes labeled from 0 to n-1 and a list of undirected edges (each edge is a pair of nodes), write a function to check whether these edges make up a valid tree.

Not sure:

Time: O(v) A tree has v nodes and we must visited them all 

Space: O(v) We are storing all the v nodes that we are visiting.
Is this the biggest DS? What about the adjacency list? O(v + e)? )

# 261. Graph Valid Tree

In [32]:
def validTree(n, edges) -> bool:
    adj = collections.defaultdict(list)
    
    for edge in edges:
        child = edge[1]
        parent = edge[0]
        
        adj[parent].append(child)
        adj[child].append(parent)
        
    q = [0]
    visited = {0}
    print(adj)
    
    while q:
        for i in range(len(q)):
            curr = q.pop(0)
            
            for node in adj[curr]:
                if node in visited:
                    return False
                
                adj[node].remove(curr)
                visited.add(node)
                q.append(node)
                
    print(adj)
    return len(visited) == n


# Test case
edges = [[0,1], [0,2], [0,3], [1,4]]
n = 5

print("Is this graph a tree: ", validTree(n, edges))

defaultdict(<class 'list'>, {0: [1, 2, 3], 1: [0, 4], 2: [0], 3: [0], 4: [1]})
defaultdict(<class 'list'>, {0: [1, 2, 3], 1: [4], 2: [], 3: [], 4: []})
Is this graph a tree:  True


# Uncategorized Yet

# 279. Perfect Squares

Given a positive integer n, find the least number of perfect square numbers (for example, 1, 4, 9, 16, ...) which sum to n.

In [33]:
def numSquares(n: int) -> int:
    if n < 2:
        return n
    
    squares = []
    i = 1
    while i*i <= n:
        squares.append(i*i)
        i += 1
    
    q = [n]
    seen = set()
    level = 0
    
    while q:
        level += 1
        for i in range(len(q)):
            curr = q.pop(0)
            if curr in seen:
                continue
            
            # Prevent repeated calculations
            seen.add(curr)
            
            for s in squares:
                if curr - s == 0:
                    return level
                
                if curr - s > 0:
                    q.append(curr - s)
                
    return level
        

In [34]:
numSquares(12)

3

# 127. Word Ladder

Given two words (beginWord and endWord), and a dictionary's word list, find the length of shortest transformation sequence from beginWord to endWord, such that:

Only one letter can be changed at a time.
Each transformed word must exist in the word list. Note that beginWord is not a transformed word.

**Idea**: Use BFS to change one character of the word of a particular index at a time.

i: 123
c: hit

ait hat hia

bit hbt hib

cit hct hic

.

.
.
zit hzt hiz

In [35]:
def ladderLength(beginWord, endWord, wordList):
    set(wordList)
    q = [(beginWord, 1)]
    visited = {beginWord}
    
    while q:
        word, ladder = q.pop(0)
        
        if word == endWord:
            return ladder
        
        for i in range(len(word)):
            chars = list(word)
            for char in "abcdefghijklmnopqrstuvwxyz":
                chars[i] = char
                
                new_word = ''.join(chars)
                
                if new_word in wordList and new_word not in visited:
                    q.append((new_word, ladder + 1))
                    visited.add(new_word)
                    
    return 0

beginWord = "hit"
endWord = "cog"
wordList = ["hot","dot","dog","lot","log","cog"]

print(ladderLength(beginWord, endWord, wordList))

5
